### ISSUE TITLE
 implement all requirements specified in the swagger.yaml file

### ISSUE THREAD

**Issue by juergenriegler** [htl-perg-2019-20-5ahif/contact-list-exercise-juergenriegler#1]
Dear Mr Stropek,

Sorry for handing in my homework a little late.
Nonetheless i wanted to inform you that i have implemented all requirements specified in the swagger file.

Greetings,
Juergen Riegler

**Comment by rstropek** [comment]
Well done, the extra point is yours.

Greetings,
Rainer Stropek.
